export default [
    {
        title: 'April Fools Day',
        details:
            'Everything is funny as long as it is happening to someone else',
        date: '2023-07-23',
        bgcolor: 'orange',
    },
    {
        title: 'Sisters Birthday',
        details: 'Buy a nice present',
        date: '2023-07-23',
        bgcolor: 'green',
        icon: 'fas fa-birthday-cake',
    },
    {
        title: 'Meeting',
        details: 'Time to pitch my idea to the company',
        date: '2023-07-24',
        time: '10:00',
        duration: 120,
        bgcolor: 'red',
        icon: 'fas fa-handshake',
    },
    {
        title: 'Lunch',
        details: 'Company is paying!',
        date: '2023-07-24',
        time: '11:30',
        duration: 90,
        bgcolor: 'teal',
        icon: 'fas fa-hamburger',
    },
    {
        title: 'Visit mom',
        details: 'Always a nice chat with mom',
        date: '2023-07-25',
        time: '17:00',
        duration: 90,
        bgcolor: 'blue-grey',
        icon: 'fas fa-car',
    },
    {
        title: 'Conference',
        details: 'Teaching Javascript 101',
        date: '2023-07-26',
        time: '08:00',
        duration: 540,
        bgcolor: 'blue',
        icon: 'fas fa-chalkboard-teacher',
    },
    {
        title: 'Girlfriend',
        details: 'Meet GF for dinner at Swanky Restaurant',
        date: '2023-07-23',
        time: '19:00',
        duration: 180,
        bgcolor: 'teal',
        icon: 'fas fa-utensils',
    },
    {
        title: 'Fishing',
        details: 'Time for some weekend R&R',
        date: '2023-07-27',
        bgcolor: 'purple',
        icon: 'fas fa-fish',
        days: 2,
    },
    {
        title: 'Vacation',
        details:
            "Trails and hikes, going camping! Don't forget to bring bear spray!",
        date: '2023-07-29',
        bgcolor: 'purple',
        icon: 'fas fa-plane',
        days: 5,
    },
];
